apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi-app
    environment: prod
  name: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
      environment: prod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fastapi-app
        environment: prod
    spec:
      containers:
      - image: akshaytredence/fastapi-demo:v8
        name: fastapi-app
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
