apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi-app
    environment: prod
spec:
  selector:
    app: fastapi-app
    environment: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
