apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-dev
  labels:
    app: fastapi-app
    environment: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fastapi-app
      environment: dev
  template:
    metadata:
      labels:
        app: fastapi-app
        environment: dev
    spec:
      containers:
        - name: fastapi-app
          image: akshaytredence/fastapi-demo:v3
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5



apiVersion: v1
kind: Service
metadata:
  name: fastapi-service-dev
  namespace: dev
  labels:
    app: fastapi-app
    environment: dev
spec:
  selector:
    app: fastapi-app
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
