name: Promote Image to Prod

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  promote:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Promote dev image to prod
        run: python scripts/promote_image.py

      - name: Create Pull Request for prod promotion
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Promote image tag from dev to prod"
          title: "Auto: Promote image tag from dev to prod"
          body: |
            Automated promotion of image tag from dev to prod environment.
            
            Triggered by merge of PR #${{ github.event.pull_request.number }}
          branch: auto-promote-prod
          delete-branch: true