name: Promote Image to Prod

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  promote:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Promote dev image to prod
        run: python scripts/promote_image.py

      - name: Commit and push updated prod deployment
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "akshaymitra-tredence"
          git config user.email "akshay.mitra@tredence.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git add manifests/prod/deployment.yaml
          git commit -m "Promote image tag from dev to prod" || echo "No changes to commit"
          git push